### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by kngy0306** [lucasoshiro/lucasoshiro.github.io#10]
## Motivation

I found Typo in this [article](https://lucasoshiro.github.io/posts-en/2024-06-17-ruby-shellscript/).

> exists = File.exists? 'My File'

Sample code described in "Feature 7: builtin file and dir operations"

## Suggestion

```diff
- File.exists? 'My File'
+ File.exist? 'My File' 
```

---

Thank you for the wonderful article!

**Comment by lucasoshiro** [comment]
Hi @kngy0306 ! 

This was not exactly a typo, as we have both `exist?` and `exists?`. I checked here what's the difference between them, and `exists?` is being deprecated. So, you're wright anyway, I just changed it (1728a3a10814e46d900b2ea71ded8833df80b3f9)!

Thanks for reading, and for the feedback!
